// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQzHMPr3oYOXLzE92fdDKSKS-Wm-5wLk',
    appId: '1:197505752892:web:c2f6082543f028621a4839',
    messagingSenderId: '197505752892',
    projectId: 'fileats-ca98b',
    authDomain: 'fileats-ca98b.firebaseapp.com',
    storageBucket: 'fileats-ca98b.firebasestorage.app',
    measurementId: 'G-80WG0S6JC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2dX4wep3b4gc503kfCyB0WNhw4LQkDhw',
    appId: '1:197505752892:android:f75da76ab62e9a8d1a4839',
    messagingSenderId: '197505752892',
    projectId: 'fileats-ca98b',
    storageBucket: 'fileats-ca98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPJSGvP_VQ0Oxw9mb6Zdh8RMhwGykBfw',
    appId: '1:197505752892:ios:e38265e1bd166e5e1a4839',
    messagingSenderId: '197505752892',
    projectId: 'fileats-ca98b',
    storageBucket: 'fileats-ca98b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPJSGvP_VQ0Oxw9mb6Zdh8RMhwGykBfw',
    appId: '1:197505752892:ios:e38265e1bd166e5e1a4839',
    messagingSenderId: '197505752892',
    projectId: 'fileats-ca98b',
    storageBucket: 'fileats-ca98b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQzHMPr3oYOXLzE92fdDKSKS-Wm-5wLk',
    appId: '1:197505752892:web:9107d2cb93f42d281a4839',
    messagingSenderId: '197505752892',
    projectId: 'fileats-ca98b',
    authDomain: 'fileats-ca98b.firebaseapp.com',
    storageBucket: 'fileats-ca98b.firebasestorage.app',
    measurementId: 'G-XG2VJVPDQJ',
  );

}